name: Run CI pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Clone github repos
        run: |
          git clone https://github.com/richwolski/euca-cutils.git
          git clone https://github.com/MAYHEM-Lab/mio.git
          git clone https://github.com/MAYHEM-Lab/cspot.git
      - name: Install CZMQ
        run: cd cspot/zmq; sh install-ubuntu-zmq.sh
      - name: Run make in repos
        run: |
          cd euca-cutils; make; cd ..
          cd mio; make; cd ..
          cd cspot; make; cd ..
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world test file
        run: |
          cd apps/hello-world;
          make;
          hw.c;