name: Run CI pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:

  single-namespace:
    runs-on: self-hosted
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
    steps:
    - name: Set up local handler
      run: cd apps/ping-pong && make && cd/cspot && ./woofc-namespace-platform &> namespace.log


  test-senspot:
    runs-on: self-hosted
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
    steps:
    - name: Test senspot-get
      run: cd apps/senspot && make && ./senspot-get -W woof://128.111.45.83/mnt/monitor/lrec.temp

  test-single-namespace:
    needs: single-namespace
    runs-on: self-hosted
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
    steps:
    - name: Test single makespace
      run: |
        cd apps/ping-pong/cspot
        ./ping-pong-start -f ping-pong-test -s 10
        tail namespace.log >> tail_single_namespace.txt
        diff tail_single_namespace.txt correct_tail_single_namespace.txt
        rm tail_single_namespace.txt