name: Run CI pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Run hello world test file
        run: |
          cd ../cspot/cspot/cspot/apps/hello-world;
          make;
          hw.c;