name: Run CI pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: self-hosted
    steps:
      - name: Clone github repos
        run: |
          git clone https://github.com/richwolski/euca-cutils.git
          git clone https://github.com/MAYHEM-Lab/mio.git
          git clone https://github.com/MAYHEM-Lab/cspot.git
      - name: Install CZMQ
        run: cd cspot/zmq; sh install-ubuntu-zmq.sh
      - name: Run make in repos
        run: |
          cd euca-cutils; make; cd ..
          cd mio; make; cd ..
          cd cspot; make; cd ..
  test:
    runs-on: self-hosted
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
    steps:
      - name: Test senspot-get
        run: ./senspot-get -W woof://128.111.45.83/mnt/monitor/lrec.temp