name: Run CI pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: macos-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Clone github repos
        run: |
          git clone https://github.com/richwolski/euca-cutils.git
          git clone https://github.com/MAYHEM-Lab/mio.git
          git clone https://github.com/MAYHEM-Lab/cspot.git
      - name: Run make in repos
        run: |
          cd euca-cutils; make
          cd mio; make
          cd cspot; make
      - name: Install zmq
        run: cd zmq; sh install-zmq.sh
  test:
    runs-on: centos-latest
    steps:
      - name: Run hello world test file
        run: |
          cd apps/hello-world;
          make;
          hw.c;