name: Run CI pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    runs-on: self-hosted
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
    steps:
      - name: Where am I
        run: mkdir hi
      - name: Test senspot-get
        run: ./senspot-get -W woof://128.111.45.83/mnt/monitor/lrec.temp