name: Run CI pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test-senspot:
    runs-on: self-hosted
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
    steps:
    - name: Test senspot-get
      run: cd cspot/apps/senspot && ./senspot-get -W woof://128.111.45.83/mnt/monitor/lrec.temp

  run-single-namespace:
    runs-on: self-hosted
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
    steps:
    - name: Run tests on single namespace
      run: |
        cd cspot/apps/ping-pong/cspot
        ./woofc-namespace-platform &> namespace.log &
        ./ping-pong-start -f ping-pong-test -s 10

  publish-single-namespace-test-results:
    runs-on: self-hosted
    uses: actions/upload-artifact@v2
    with:
      name: single-namespace-test
      path: /home/actions-runner/_work/cspot/cspot/apps/ping-pong/cspot/namespace.log

  # test-single-namespace-output:
  #   needs: run-single-namespace
  #   runs-on: self-hosted
  #   env:
  #     LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
  #   steps:
  #   - name: Check output from single namespace tests
  #     run: |
  #       cd cspot/apps/ping-pong/cspot
  #       tail namespace.log >> tail_single_namespace.txt
  #       diff tail_single_namespace.txt correct_tail_single_namespace.txt
  #       rm tail_single_namespace.txt

