name: Run CI pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test-senspot:
    runs-on: self-hosted
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
    steps:
    - name: Test senspot-get
      run: cd cspot/apps/senspot && ./senspot-get -W woof://128.111.45.83/mnt/monitor/lrec.temp

  test-single-namespace:
    runs-on: self-hosted
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
    steps:
    - name: Test single makespace
      run: |
        cd cspot/apps/ping-pong/cspot
        ./woofc-namespace-platform &> namespace.log &
        ./ping-pong-start -f ping-pong-test -s 10